levels[3] = {
  chapters = {
    { story = "Allo Emma ? … Euh oui ça va … j’ai bien emménagé oui mais … attends, écoute. Il faut que je te parle … C’est à propos du coquillage … Oui, celui-là ... Écoute Emma, c’est con je sais mais le coquillage m’a transmis un nouveau message où il parlait de toi : il dit que tu es en danger … J’aimerais bien mais non, j’ai rien fumé … Mais non, j’essaie pas de te faire flipper ! … Emma calme-toi ! Je sais que c’est complètement con mais imagine si c’est vrai ! … Emma ? Emma ? … Et merde.",
      illustration = "resources/images/shell.png"
    },
    { story = "Samedi 3 mars\n\nJe n’ai presque pas dormi depuis jeudi. Je crois ne jamais avoir bu autant de café en si peu de temps. Des jours et des nuits à essayer de comprendre ce qu’il m’arrive. C’est quoi ce foutu bordel ? J’ai épuisé toutes les pistes qui me sont venues : histoires de marins, vieilles légendes bizarres, communications aliens, … je me suis même tapé des pavés entiers sur la biologie des mollusques, et toujours aucune information concluante sur ce maudit coquillage ! Et Emma qui ne répond pas ... Je ferais mieux d’aller me coucher.",
      illustration = "resources/images/shell.png"
    }
  },
  sentence = "Si tu ne fais rien, tu perdras ton amie à cause des vents violents",
  fake_text = "Sa vie est connue uniquement par deux articles de la Souda, une encyclopédie byzantine du Xe siècle. Fils d'un dénommé Crinos, il est natif de Samos. Il organise la colonisation de l'île d'Amorgos, dans les Cyclades, où il fonde trois cités, Minoa, Égialée et Arcésiné, lui-même s'établissant à Minoa. L'histoire n'est pas nécessairement véridique, car elle rappelle étrangement la biographie d'Archiloque, censé avoir pris part à la fondation de Thasos, colonie de Paros. En outre, seule Minoa est de fondation samienne, Égialée et Arcésiné ayant été fondées par Naxos. L'histoire pourrait avoir été inventée pour réconcilier deux traditions, l'une faisant de Samos la patrie de Sémonide, l'autre citant Amorgos. La date de son floruit apogée n'est pas connue avec certitude. Les chronographes citent plusieurs dates : la 20e olympiade selon Clément d'Alexandrie, la première année de la 29e olympiade selon Jérôme de Stridon dans sa Chronique, la 23e olympiade selon Cyrille d'Alexandrie. La Souda le place 490 ans après la guerre de Troie, soit au VIIe siècle av. J.-C. Les commentateurs modernes retiennent généralement qu'il est à peu près contemporain d'Archiloque. On a toutefois soutenu que les images retenues par Sémonide dans son poème sur les femmes trahissaient sa connaissance de la théorie ionienne sur les quatre grands éléments ; pour cette raison notamment, Sémonide donc plutôt être placé au VIe siècle av. J.-C.10",
  endIllustration = "resources/images/shellDestroyed.png",
  endText = "Vendredi 16 mars.\n\nUne tempête s’est déclenchée dans l’Ouest. Emma est portée disparue. Coquillage de malheur ! Sans toi, rien de tout ça ne serait arrivé ! D’un coup de marteau, je brise sa coquille. Ça ne me rendra pas Emma, mais ça soulage."
}