sentences = {
  "Morgan s'il-te-plait emmène-moi avec toi",
  "Ton amie la plus chère court un grand danger",
  "Si tu ne fais rien, tu perdras ton amie à cause des vents violents",
  "La mer s’apprête à engloutir ton amie, et tu restes là ?"
}

fake_texts = {
  "Jess Barker entame sa carrière d'acteur au théâtre et joue notamment à Broadway (New York) dans quatre pièces, la première en 1934, les deux dernières en 1942. Entretemps, il collabore à Vous ne l'emporterez pas avec vous de Moss Hart et George S. Kaufman, représentée 838 fois de décembre 1936 à décembre 1938, aux côtés entre autres de Josephine Hull, Oscar Polk, George Tobias, Henry Travers et Frank Wilcox ; il y tient le rôle de Tony Kirby, repris par James Stewart dans l'adaptation au cinéma de 1938, réalisée par Frank Capra sous le même titre. Au grand écran, il débute sous le nom de Philip Barker (non réutilisé) dans La Fille du bois maudit d'Henry Hathaway (avec Sylvia Sidney et Fred MacMurray), sorti en 1936. Puis il contribue à vingt-six autres films américains, sortis entre 1943 et 1977, dont quatre westerns. Mentionnons également L'Exubérante Smoky de Dudley Nichols (son troisième film, 1943, avec Olivia de Havilland et Sonny Tufts), La Rue rouge de Fritz Lang (1945, avec Edward G. Robinson et Joan Bennett), Le Livre noir d'Anthony Mann (1949, avec Richard Basehart interprétant Robespierre et Robert Cummings, lui-même personnifiant Saint-Just), ou encore Celui qui n'existait pas de William Castle (1964, avec Barbara Stanwyck et Robert Taylor). À la télévision, Jess Barker apparaît dans quinze séries de 1951 à 1972, dont Perry Mason (deux épisodes, 1961-1965). Il est le premier mari de l'actrice Susan Hayward, qu'il épouse en 1944, mais dont il divorce en 1954 (des jumeaux sont nés en 1945 de leur union).",
  "Le moteur Willys L134 Go-Devil a évolué pour devenir le F134 en 1950. Ce moteur développe une puissance de 75 Ch/56kW à 4 000 tr/min et un couple de 155 Nm à 2 000 tr/min avec un rapport de compression de 7,5:1. La puissance et le couple sont ramenés à 72 Ch/54 kW et 152 Nm lorsque le taux de compression est abaissé à 6,9:1. L'alésage et la course sont les mêmes que ceux du moteur L134 donnait une cylindrée de 2 199 cm3. Le F4-134 a été lancé en 1950 avec la nouvelle Jeep Willys Truck. Avec ce moteur la désignation du modèle devient 4-73. Cependant, il n'a pas été monté dans la gamme CJ jusqu'à la CJ-3B en 1953 qui avait un capot surélevé spécifique pour accueillir le moteur beaucoup plus volumineux. Le moteur sera produit jusqu'en 1971, après qu'American Motors Corporation ait racheté Kaiser Jeep.",
  "Sa vie est connue uniquement par deux articles de la Souda, une encyclopédie byzantine du Xe siècle. Fils d'un dénommé Crinos, il est natif de Samos. Il organise la colonisation de l'île d'Amorgos, dans les Cyclades, où il fonde trois cités, Minoa, Égialée et Arcésiné, lui-même s'établissant à Minoa. L'histoire n'est pas nécessairement véridique, car elle rappelle étrangement la biographie d'Archiloque, censé avoir pris part à la fondation de Thasos, colonie de Paros. En outre, seule Minoa est de fondation samienne, Égialée et Arcésiné ayant été fondées par Naxos. L'histoire pourrait avoir été inventée pour réconcilier deux traditions, l'une faisant de Samos la patrie de Sémonide, l'autre citant Amorgos. La date de son floruit apogée n'est pas connue avec certitude. Les chronographes citent plusieurs dates : la 20e olympiade selon Clément d'Alexandrie, la première année de la 29e olympiade selon Jérôme de Stridon dans sa Chronique, la 23e olympiade selon Cyrille d'Alexandrie. La Souda le place 490 ans après la guerre de Troie, soit au VIIe siècle av. J.-C. Les commentateurs modernes retiennent généralement qu'il est à peu près contemporain d'Archiloque. On a toutefois soutenu que les images retenues par Sémonide dans son poème sur les femmes trahissaient sa connaissance de la théorie ionienne sur les quatre grands éléments ; pour cette raison notamment, Sémonide donc plutôt être placé au VIe siècle av. J.-C.10",
  "Apparu au Japon entre le VIe siècle et le VIIIe siècle grâce aux échanges avec l’Empire chinois, l’art de l’emaki se diffusa largement auprès de l’aristocratie à l’époque de Heian. Un emaki se compose d’un ou plusieurs longs rouleaux de papier narrant une histoire au moyen de textes et de peintures de style yamato-e. Le lecteur découvre le récit en déroulant progressivement les rouleaux avec une main tout en le ré-enroulant avec l’autre main, de droite à gauche (selon le sens d’écriture du japonais), de sorte que seule une portion de texte ou d’image d’une soixantaine de centimètres est visible. La narration suppose un enchaînement de scènes dont le rythme, la composition et les transitions relèvent entièrement de la sensibilité et de la technique de l’artiste. Les thèmes des récits étaient très variés : illustrations de romans, de chroniques historiques, de textes religieux, de biographies de personnages célèbres, d’anecdotes humoristiques ou fantastiques"
}