sentences = {
  "Morgan s'il-te-plait emmène-moi avec toi",
  "Ton amie la plus chère court un grand danger",
  "troisième phrase à deviner"
}

fake_texts = {
  "Jess Barker entame sa carrière d'acteur au théâtre et joue notamment à Broadway (New York) dans quatre pièces, la première en 1934, les deux dernières en 1942. Entretemps, il collabore à Vous ne l'emporterez pas avec vous de Moss Hart et George S. Kaufman, représentée 838 fois de décembre 1936 à décembre 1938, aux côtés entre autres de Josephine Hull, Oscar Polk, George Tobias, Henry Travers et Frank Wilcox ; il y tient le rôle de Tony Kirby, repris par James Stewart dans l'adaptation au cinéma de 1938, réalisée par Frank Capra sous le même titre. Au grand écran, il débute sous le nom de Philip Barker (non réutilisé) dans La Fille du bois maudit d'Henry Hathaway (avec Sylvia Sidney et Fred MacMurray), sorti en 1936. Puis il contribue à vingt-six autres films américains, sortis entre 1943 et 1977, dont quatre westerns. Mentionnons également L'Exubérante Smoky de Dudley Nichols (son troisième film, 1943, avec Olivia de Havilland et Sonny Tufts), La Rue rouge de Fritz Lang (1945, avec Edward G. Robinson et Joan Bennett), Le Livre noir d'Anthony Mann (1949, avec Richard Basehart interprétant Robespierre et Robert Cummings, lui-même personnifiant Saint-Just), ou encore Celui qui n'existait pas de William Castle (1964, avec Barbara Stanwyck et Robert Taylor). À la télévision, Jess Barker apparaît dans quinze séries de 1951 à 1972, dont Perry Mason (deux épisodes, 1961-1965). Il est le premier mari de l'actrice Susan Hayward, qu'il épouse en 1944, mais dont il divorce en 1954 (des jumeaux sont nés en 1945 de leur union).",
  "Le moteur Willys L134 Go-Devil a évolué pour devenir le F134 en 1950. Ce moteur développe une puissance de 75 Ch/56kW à 4 000 tr/min et un couple de 155 Nm à 2 000 tr/min avec un rapport de compression de 7,5:1. La puissance et le couple sont ramenés à 72 Ch/54 kW et 152 Nm lorsque le taux de compression est abaissé à 6,9:1. L'alésage et la course sont les mêmes que ceux du moteur L134 donnait une cylindrée de 2 199 cm3. Le F4-134 a été lancé en 1950 avec la nouvelle Jeep Willys Truck. Avec ce moteur la désignation du modèle devient 4-73. Cependant, il n'a pas été monté dans la gamme CJ jusqu'à la CJ-3B en 1953 qui avait un capot surélevé spécifique pour accueillir le moteur beaucoup plus volumineux. Le moteur sera produit jusqu'en 1971, après qu'American Motors Corporation ait racheté Kaiser Jeep."
}